carriage/config/routes.rb
Rails.application.routes.draw do
  root 'real_estates#index'
  resources :real_estates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

carriage/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

carriage/app/models/real_estate.rb
# == Schema Information
#
# Table name: real_estates
#
#  id         :integer          not null, primary key
#  street     :string
#  city       :string
#  zip        :integer
#  state      :string
#  beds       :integer
#  baths      :integer
#  sq_ft      :integer
#  category   :integer
#  sale_date  :date
#  price      :integer
#  lat        :float
#  lng        :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class RealEstate < ApplicationRecord

validates :street, :city, :category, presence: true
validates :zip, :beds, :baths, :sq_ft, :price, :lat, :lng, numericality: true

validates :zip, length: { is: 5 }



enum category: [:Residential, :Condo, :Multi_Family, :Unknown]

self.per_page = 20


scope :street, -> (street) { where("street like ?", "%#{street}%")}
scope :category, -> (category) { where(category: category)}
scope :price_max, -> (price_max) { where ("price <= #{price_max}") }
scope :price_min, -> (price_min) { where ("price >= #{price_min}") }
scope :sq_max, -> (sq_max) { where ("sq_ft <= #{sq_max}") }
scope :sq_min, -> (sq_min) { where ("sq_ft >= #{sq_min}") }
end

carriage/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

carriage/app/controllers/real_estates_controller.rb
class RealEstatesController < ApplicationController
  before_action :set_real_estate, only: [:show, :edit, :update, :destroy]

  # GET /real_estates
  # GET /real_estates.json
  def index
  
    @real_estates = RealEstate.all
    filtering_params(params).each do |key, value|
      @real_estates = @real_estates.public_send(key, value) if value.present?
    end
    @real_estates = @real_estates.page(params[:page])
  end

  # GET /real_estates/1
  # GET /real_estates/1.json
  def show
  end

  # GET /real_estates/new
  def new
    @real_estate = RealEstate.new
  end

  # GET /real_estates/1/edit
  def edit
  end

  # POST /real_estates
  # POST /real_estates.json
  def create
    @real_estate = RealEstate.new(real_estate_params)

    respond_to do |format|
      if @real_estate.save
        format.html { redirect_to @real_estate, notice: 'Real estate was successfully created.' }
        format.json { render :show, status: :created, location: @real_estate }
      else
        format.html { render :new }
        format.json { render json: @real_estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /real_estates/1
  # PATCH/PUT /real_estates/1.json
  def update
    respond_to do |format|
      if @real_estate.update(real_estate_params)
        format.html { redirect_to @real_estate, notice: 'Real estate was successfully updated.' }
        format.json { render :show, status: :ok, location: @real_estate }
      else
        format.html { render :edit }
        format.json { render json: @real_estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /real_estates/1
  # DELETE /real_estates/1.json
  def destroy
    @real_estate.destroy
    respond_to do |format|
      format.html { redirect_to real_estates_url, notice: 'Real estate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_real_estate
      @real_estate = RealEstate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def real_estate_params
      params.require(:real_estate).permit(:street, :city, :zip, :state, :beds, :baths, :sq_ft, :category, :sale_date, :price, :lat, :lng)
    end
    
    def filtering_params(params)
      params.slice(:category, :price_min, :price_max, :street, :sq_min, :sq_max)
    end
end

carriage/app/helpers/application_helper.rb
module ApplicationHelper
end

carriage/app/helpers/real_estates_helper.rb
module RealEstatesHelper
end

carriage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carriage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

carriage/app/views/real_estates/_form.html.erb
<%= form_for(real_estate) do |f| %>
  <% if real_estate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(real_estate.errors.count, "error") %> prohibited this real_estate from being saved:</h2>

      <ul>
      <% real_estate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.number_field :zip %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :beds %>
    <%= f.number_field :beds %>
  </div>

  <div class="field">
    <%= f.label :baths %>
    <%= f.number_field :baths %>
  </div>

  <div class="field">
    <%= f.label :sq_ft %>
    <%= f.number_field :sq_ft %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.select :category, options_for_select(RealEstate.categories.keys, params[:category]) %>
  </div>

  <div class="field">
    <%= f.label :sale_date %>
    <%= f.date_select :sale_date %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :lat %>
    <%= f.text_field :lat %>
  </div>

  <div class="field">
    <%= f.label :lng %>
    <%= f.text_field :lng %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

carriage/app/views/real_estates/edit.html.erb
<h1>Editing Real Estate</h1>

<%= render 'form', real_estate: @real_estate %>

<%= link_to 'Show', @real_estate %> |
<%= link_to 'Back', real_estates_path %>

carriage/app/views/real_estates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Real Estates</h1>


<%= form_tag real_estates_path, :method => 'get' do %>
  <%= content_tag :label do %>
    Street:
    <%= text_field_tag :street, params[:street] %>
  <% end %>
  
  type: <%= select_tag :category, options_for_select(RealEstate.categories.keys, params[:category]), include_blank: "ALL"  %>
  Max price: <%= number_field_tag :price_max, params[:price_max] %>
  Min price: <%= number_field_tag :price_min, params[:price_min] %>
  Max sq_feet: <%= number_field_tag :sq_max, params[:sq_max], class: 'input-small' %>
  Min sq_feet: <%= number_field_tag :sq_min, params[:sq_min] %>
  <%= submit_tag "Search", class: "btn", name: nil %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>Zip</th>
      <th>State</th>
      <th>Beds</th>
      <th>Baths</th>
      <th>Sq ft</th>
      <th>Category</th>
      <th>Sale date</th>
      <th>Price</th>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @real_estates.each do |real_estate| %>
      <tr>
        <td><%= real_estate.street %></td>
        <td><%= real_estate.city %></td>
        <td><%= real_estate.zip %></td>
        <td><%= real_estate.state %></td>
        <td><%= real_estate.beds %></td>
        <td><%= real_estate.baths %></td>
        <td><%= real_estate.sq_ft %></td>
        <td><%= real_estate.category %></td>
        <td><%= real_estate.sale_date %></td>
        <td><%= real_estate.price %></td>
        <td><%= real_estate.lat %></td>
        <td><%= real_estate.lng %></td>
        <td><%= link_to 'Show', real_estate %></td>
        <td><%= link_to 'Edit', edit_real_estate_path(real_estate) %></td>
        <td><%= link_to 'Destroy', real_estate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @real_estates %>
    </div>
    <%= will_paginate @real_estates, :container => false %>
  </div>

<%= link_to 'New Real Estate', new_real_estate_path, :class => "btn"  %>

carriage/app/views/real_estates/new.html.erb
<h1>New Real Estate</h1>

<%= render 'form', real_estate: @real_estate %>

<%= link_to 'Back', real_estates_path %>

carriage/app/views/real_estates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @real_estate.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @real_estate.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @real_estate.zip %>
</p>

<p>
  <strong>State:</strong>
  <%= @real_estate.state %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @real_estate.beds %>
</p>

<p>
  <strong>Baths:</strong>
  <%= @real_estate.baths %>
</p>

<p>
  <strong>Sq ft:</strong>
  <%= @real_estate.sq_ft %>
</p>

<p>
  <strong>Category:</strong>
  <%= @real_estate.category %>
</p>

<p>
  <strong>Sale date:</strong>
  <%= @real_estate.sale_date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @real_estate.price %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @real_estate.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @real_estate.lng %>
</p>

<%= link_to 'Edit', edit_real_estate_path(@real_estate) %> |
<%= link_to 'Back', real_estates_path %>